# Generated by Django 6.0 on 2025-12-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tag', models.CharField(blank=True, help_text='Например: NOIR · AUTOMATIC', max_length=255, verbose_name='Тег над картинкой')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(help_text='Хранится как целое число, без копеек', verbose_name='Цена, сум')),
                ('badge', models.CharField(blank=True, help_text='Например: "Bestseller", "New", "Limited"', max_length=50, verbose_name='Бейдж')),
                ('image', models.ImageField(blank=True, null=True, upload_to='watches/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Меньше число — выше в списке', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Часы',
                'verbose_name_plural': 'Часы',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
