# Generated by Django 6.0 on 2025-12-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показывать на главной странице среди первых трёх', verbose_name='В избранной подборке'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.IntegerField(help_text='Хранится как целое число, без копеек', verbose_name='Цена, сум'),
        ),
    ]
