# Generated by Django 6.0 on 2025-12-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_watch_is_featured_alter_watch_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='is_hero',
            field=models.BooleanField(default=False, help_text='Эта модель показывается в большом блоке сверху', verbose_name='Показывать в hero'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показывать в подборке на главной', verbose_name='В избранной подборке'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.IntegerField(help_text='Хранится как целое число, без копеек', verbose_name='Цена, ₽'),
        ),
    ]
