# Generated by Django 6.0 on 2025-12-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_watch_is_hero_alter_watch_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='currency',
            field=models.CharField(default='сум', max_length=10, verbose_name='Валюта'),
        ),
    ]
