# Generated by Django 6.0 on 2025-12-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_watch_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='currency',
            field=models.CharField(default='сум', help_text='Например: сум, ₽, $, €', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Эта модель будет попадать в Featured Timepieces', verbose_name='Показывать в подборке'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='is_hero',
            field=models.BooleanField(default=False, help_text='Эта модель будет отображаться в большом блоке наверху сайта', verbose_name='Показывать в hero-блоке'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.IntegerField(help_text='Хранится как целое число, без копеек', verbose_name='Цена'),
        ),
    ]
