# Generated by Django 6.0 on 2025-12-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('waiting', 'В ожидании подтверждения'), ('delivered', 'Доставлен'), ('canceled', 'Отменён')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
    ]
